CREATE TABLE IF NOT EXISTS `likes` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `user_from` varchar(255) DEFAULT NULL,
  `user_to` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=111 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `message` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `id_talk` int(6) NOT NULL,
  `username` varchar(255) DEFAULT NULL,
  `date` varchar(200) NOT NULL,
  `message` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=129 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `talk` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `username1` varchar(255) DEFAULT NULL,
  `username2` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user` (
  `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
  `login` varchar(255) DEFAULT NULL,
  `password` text,
  `fname` varchar(255) NOT NULL,
  `lname` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `gender` varchar(1) DEFAULT NULL,
  `interested_in` varchar(15) DEFAULT NULL,
  `bio` text,
  `activated` varchar(255) DEFAULT NULL,
  `rights` int(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8mb4;

INSERT INTO `likes` (`id`,`user_from`,`user_to`) VALUES (106,'undefined','tincidunt');
INSERT INTO `likes` (`id`,`user_from`,`user_to`) VALUES (108,'jubarbie','tincidunt');
INSERT INTO `likes` (`id`,`user_from`,`user_to`) VALUES (110,'jubarbie','facilisis');

INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (113,106,'jubarbie','1509631495783','oui\n');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (114,106,'jubarbie','1509631520915','<script>alert(\'oui\');</script>');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (115,106,'jubarbie','1509631663195','yo\n');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (116,106,'jubarbie','1509631667443','bien ?');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (117,106,'jubarbie','1509631762982','oui et toi ?');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (118,106,'jubarbie','1509636891310','ca va oui merci');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (119,106,'jubarbie','1509637551109','yo');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (120,106,'jubarbie','1509640806902','test');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (121,106,'jubarbie','1509640833994','test\n');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (122,106,'jubarbie','1509640943401','test');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (123,106,'jubarbie','1509641014002','love you');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (124,106,'jubarbie','1509641037178','test');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (125,106,'jubarbie','1509641043318','test');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (126,106,'jubarbie','1509641129634','YoYoyoyo');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (127,106,'jubarbie','1509641312117','love you');
INSERT INTO `message` (`id`,`id_talk`,`username`,`date`,`message`) VALUES (128,106,'marchall','1509641328395','hahah');

INSERT INTO `talk` (`id`,`username1`,`username2`) VALUES (105,'jubarbie','tincidunt');
INSERT INTO `talk` (`id`,`username1`,`username2`) VALUES (106,'jubarbie','marchall');
INSERT INTO `talk` (`id`,`username1`,`username2`) VALUES (107,'Aenean','jubarbie');
INSERT INTO `talk` (`id`,`username1`,`username2`) VALUES (108,'marchall','marchall');

INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (14,'tincidunt','KBI60RZD5FU','Signe','Quin','euismod.in@fringillacursuspurus.edu','F','F','a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (16,'Aenean','MTG37IIL0KU','Bruce','Leroy','mollis@orciadipiscingnon.ca','M','F','nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (18,'facilisis','MAT13OHY0HE','Tanya','Taylor','Mauris@sagittis.net','F','F','imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (19,'eu','XDC98NAB6FX','Belle','Kennan','neque.Morbi.quis@DonecestNunc.edu','F','M','mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (20,'adipiscing','PKG70YIM8QD','Rachel','Harlan','Quisque.purus@malesuadafames.org','F','M','ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (22,'mus.','DYK94DZI9CZ','Wylie','Mohammad','dignissim@Vestibulumante.edu','F','F','non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (23,'sit','FTC33VYR9VR','Forrest','Murphy','adipiscing.fringilla.porttitor@aliquamadipiscinglacus.org','F','M','eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (24,'libero','OBU62KVM8GC','Garrett','David','sed@velitdui.net','F','F','et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (25,'nisl.','VQR75YZG3FV','Kaitlin','Felix','facilisis@Praesenteu.co.uk','M','F','ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (26,'dolor','FPW82EKD1HJ','Jeremy','Shelley','risus.varius@tempusnon.edu','F','M','Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (27,'Sed','BTF32ZFP6NM','Noah','Jescie','magna.Lorem.ipsum@lectus.net','M','F','metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (28,'mauris','OLX39LIW9CU','Basil','Hedda','eu.arcu@Nuncsollicitudincommodo.net','F','F','in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (29,'amet,','GUU00FVE2AA','Byron','TaShya','ligula.Nullam@enimMauris.com','F','M','Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (30,'rutrum.','PQJ70AXF3RA','Josephine','Porter','penatibus.et@estac.com','F','F','pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (31,'Nam','ICY00HSU1CT','Herrod','Leandra','mauris@acrisusMorbi.ca','M','F','eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (32,'senectus','KCA53ESM9NW','Hop','Laura','varius.ultrices@milorem.edu','F','F','magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (33,'Nullam','ZHS86DEE6LQ','Logan','Yael','dolor.Fusce.mi@turpisegestasFusce.edu','F','F','netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (34,'tincidunt','YNZ78RXL1TV','Mona','Dolan','sem.Pellentesque.ut@nostraperinceptos.org','F','F','risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (35,'at','VUL29WAC4KQ','Allen','Tarik','Vivamus.rhoncus@orciadipiscingnon.edu','F','F','mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (37,'non,','NUY69DAZ5MT','McKenzie','Shafira','Suspendisse.aliquet@adipiscinglobortis.edu','F','F','Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (38,'in','ZJX05AJB0FI','Tatum','Aladdin','parturient.montes.nascetur@auctor.org','F','F','Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (39,'Sed','CCH38MAM3UD','Fiona','Prescott','nunc@ac.com','F','M','nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (40,'consequat','HCK34SSG9QZ','Tanisha','Moses','luctus.ipsum.leo@NuncmaurisMorbi.com','M','F','cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (41,'ut,','HYX19PYT0HD','Rana','Donovan','nisi.Mauris@lobortisauguescelerisque.co.uk','F','M','semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (42,'Duis','RAV89JKI7VM','Hop','Carol','sem.molestie.sodales@ipsumsodales.net','F','F','vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (43,'est,','ZBW11QZE1ZS','Felix','Yuli','ut.cursus.luctus@euodio.ca','F','M','eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (44,'hendrerit','MYV62EBP8SH','Blaine','Curran','purus.in.molestie@mus.co.uk','F','F','eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (45,'mi','BQR14TKX8IF','Evangeline','Kelsey','cursus.diam@purusinmolestie.edu','M','M','semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (46,'risus.','QRV87ZVJ0ZX','Brendan','Shana','volutpat.nunc@arcuSedet.ca','F','F','consectetuer','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (48,'libero.','AGH84EXG3ML','Howard','Sierra','mi.fringilla.mi@luctussit.org','M','F','quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (49,'justo.','MVM09DYY3JC','Tyler','Bertha','Vestibulum.ante.ipsum@ante.com','F','F','montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (50,'sem.','RWN13MFZ1SF','Deborah','Chandler','et@idrisusquis.ca','M','M','sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (51,'non,','PJK49FME3EA','Angelica','Cole','enim.commodo.hendrerit@senectusetnetus.org','M','F','non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (53,'sapien.','IKC59AWL5JI','Jenna','Jaquelyn','Aliquam@elementum.net','F','F','sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (54,'Mauris','QMO71NPI8SL','Olivia','Imani','nunc@cursusNunc.net','M','M','placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (55,'eget','URS48LRL5QG','Brennan','Maite','molestie.dapibus.ligula@dignissim.net','M','F','non arcu. Vivamus sit amet risus. Donec egestas. Aliquam','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (56,'sit','GVC91PJA5JA','Jameson','Karleigh','eleifend.egestas@nostraper.net','F','M','Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (57,'luctus.','BEL55TLE4FV','Demetrius','Talon','at.arcu.Vestibulum@NulladignissimMaecenas.net','M','M','pharetra, felis eget varius ultrices,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (58,'felis','NPA82VGN7TO','Isaiah','Samantha','in.lobortis@euismodin.co.uk','M','M','tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (59,'sed','KPD68UTD6XS','Dacey','Ryder','placerat.velit.Quisque@ultricesaauctor.edu','M','F','eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (60,'fames','TMT84AXJ6IZ','Brianna','Miriam','ac.mattis.velit@lectusrutrum.edu','M','M','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (61,'erat.','ZCT74PBC0LC','Jordan','Justin','sagittis.augue@IncondimentumDonec.com','F','F','Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (62,'Aliquam','ULE15FAL3MI','Ginger','Joy','neque.Morbi@loremipsumsodales.net','F','M','eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (63,'lorem,','YRK63BQD8VM','Melissa','Xerxes','dignissim@Etiambibendumfermentum.org','F','M','lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (64,'augue.','JTM90ACT1BS','Mohammad','Adrienne','sit.amet.consectetuer@urna.org','F','M','erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (65,'magna.','FWR46EBJ1VW','Lydia','Marvin','nunc.ullamcorper.eu@necquamCurabitur.co.uk','M','F','eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (66,'at','KBW55NGU1GZ','Abraham','Latifah','dis.parturient@velitQuisque.edu','F','F','eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (67,'fringilla','LIE26XPT3GZ','Bethany','Paloma','non.lobortis@mauris.org','M','F','egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (68,'egestas','JFJ74TQS4MB','Francesca','Unity','turpis@nibhDonecest.ca','M','M','sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (69,'tellus','AXC27ZNR4CT','Arsenio','Bradley','eu.tellus.Phasellus@augueSed.com','F','M','diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (70,'parturient','QRQ54IFY8UG','Aaron','Selma','tincidunt.nunc@Crasvulputatevelit.edu','F','F','auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (71,'faucibus','ILB67PEK9JU','Justin','Walter','leo.Morbi.neque@InfaucibusMorbi.com','F','F','magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (72,'nisl','OUK00TVQ4PM','Jared','Aimee','a.tortor.Nunc@egestasblandit.edu','F','M','tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (73,'Sed','KMW37IFD8DR','Patrick','Ginger','erat@non.net','F','F','est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (74,'risus.','KEC70QSF6WV','Charissa','Alea','Suspendisse@vulputate.co.uk','F','F','montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (75,'velit.','XVY80GWF8FQ','Thomas','Gavin','Vestibulum.ante@atfringillapurus.edu','F','M','Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (77,'odio.','BMX28FNB6KA','Drew','Melissa','inceptos.hymenaeos.Mauris@duiCraspellentesque.co.uk','F','F','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (78,'Etiam','TAQ34HVD7CT','Hasad','Darius','erat@Fuscealiquetmagna.ca','F','M','auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (79,'eget','IIB29QGD5GD','Thomas','Chava','eget.tincidunt.dui@eleifend.com','M','F','arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (80,'tincidunt,','FAZ53JQK7NI','Barry','Mannix','sagittis.augue.eu@amet.co.uk','M','M','vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (81,'erat,','EYG86FPO3XD','Philip','Alfreda','eu.dolor@facilisisloremtristique.edu','M','F','malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (82,'neque','ZLO29MDZ3LI','Kelsey','Meredith','consequat.nec@vel.ca','M','M','diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (83,'neque','HIQ58AHL7XE','Malachi','Xena','arcu@adipiscingnon.net','M','M','vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (84,'magna.','INL64YCV6FG','Tatyana','Gretchen','vel@ligulaAeneangravida.co.uk','M','F','nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris.','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (85,'Vestibulum','EDI61BQP3WD','Ian','Axel','Phasellus@Sednec.net','F','F','dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (86,'Etiam','OQW25JCN9BH','Clayton','Jermaine','dolor.egestas.rhoncus@sapiencursus.net','M','F','ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (87,'pede,','KNJ38ZRI7SQ','Perry','Ava','lacus@lobortisquispede.co.uk','M','M','interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (89,'adipiscing','MWH45IIA5NP','Grant','Dean','ipsum.porta@nibhsit.org','F','F','gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (90,'Quisque','GBU81CUX8BC','Maxwell','Amethyst','fringilla.cursus@necquamCurabitur.edu','F','F','sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (92,'in','KTA56FLK0UP','Wanda','Ariana','vehicula.risus.Nulla@volutpat.org','M','F','at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (93,'lorem','PHN45EMW8UJ','Tashya','Hedley','Maecenas.iaculis.aliquet@InfaucibusMorbi.edu','F','F','odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (94,'diam','NGD07FDA6LF','Tarik','Jacob','sit.amet.ante@Proin.org','M','M','aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (95,'torquent','RIF82CSJ3HN','Eve','Declan','felis.Donec.tempor@nislMaecenasmalesuada.net','M','M','Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (96,'Mauris','FEH32IHM1LN','Raymond','Baker','quis.pede.Praesent@sapienmolestieorci.ca','M','F','varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (97,'euismod','HOP70HYC4JR','Julie','Beverly','facilisis.Suspendisse.commodo@gravidanon.com','F','M','eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (98,'Nunc','GWM87VIQ5NB','Dillon','Cally','In@temporarcuVestibulum.ca','M','F','est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (99,'arcu.','LXF21APG8WR','Olympia','Cheyenne','egestas@idliberoDonec.co.uk','M','F','nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (100,'ipsum','MFA12BKM0HW','Xander','Matthew','cursus.et.eros@liberoat.ca','F','F','vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est,','activated',1);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (101,'jubarbie','$2a$10$vtdJOptKqDxpfK.nO5t7xO2hR4/vojekgQe.XBazhqXWsDlTWs97S','Jules','Barbier','jubarbie@student.42.fr','M','M','I\'m the administrator of this app','activated',0);
INSERT INTO `user` (`id`,`login`,`password`,`fname`,`lname`,`email`,`gender`,`interested_in`,`bio`,`activated`,`rights`) VALUES (105,'marchall','$2a$10$otYZIoZ6RazrStSZ9U56DODgjk56SL1DHjx3nnYY53xp.chph6AWK','','','jules.barbier.fr@gmail.com','','','','activated',1);